(ns memobook.vocab)

(defn make-tagged-item
  [item & tags]
  {:data item
   :tags tags
   :type :word})

(def vocab
  (vec
    (concat
      (map #(make-tagged-item % "Genki Lesson 1")
           [["あの" "あの" "um..."]
            ["今" "いま" "now"]
            ["英語" "えいご" "English (language)"]
            ["学生" "がくせい" "student"]
            ["〜語" "〜ご" "language"]
            ["高校" "こうこう" "high school"]
            ["午後" "ごご" "P.M."]
            ["午前" "ごぜん" "A.M."]
            ["〜歳" "〜さい" "...years old"]
            ["〜さん" "〜さん" "Mr./Ms...."]
            ["〜時" "〜じ" "o'clock"]
            ["〜人" "〜じん" "people"]
            ["先生" "せんせい" "teacher; Professor ..."]
            ["専攻" "せんこう" "major"]
            ["そうです" "そうです" "That's right."]
            ["大学" "だいがく" "college; university"]
            ["電話" "でんわ" "telephone"]
            ["友達" "ともだち" "friend"]
            ["名前" "なまえ" "name"]
            ["なん／なに" "何" "what"]
            ["日本" "にほん" "Japan"]
            ["〜年生" "〜ねんせい" "...year student"]
            ["はい" "はい" "yes"]
            ["半" "はん" "half"]
            ["番号" "ばんごう" "number"]
            ["留学生" "りゅうがくせい" "international student"]
            ["私" "わたし" "I"]
            ["アメリカ" "アメリカ" "U.S.A."]
            ["イギリス" "イギリス" "Britain"]
            ["オーストラリア" "オーストラリア" "Australia"]
            ["韓国" "かんこく" "Korea"]
            ["スウェーデン" "スウェーデン" "Sweden"]
            ["中国" "ちゅうごく" "China"]
            ["科学" "かがく" "science"]
            ["アジア研究" "アジアけんきゅう" "Asian studies"]
            ["国際関係" "こくさいかんけい" "international relations"]
            ["コンピューター" "コンピューター" "computer"]
            ["人類学" "じんるいがく" "anthropology"]
            ["政治" "せいじ" "politics"]
            ["ビジネス" "ビジネス" "business"]
            ["文学" "ぶんがく" "literature"]
            ["歴史" "れきし" "history"]
            ["仕事" "しごと" "job; work; occupation"]
            ["医者" "いしゃ" "doctor"]
            ["会社員" "かいしゃいん" "office worker"]
            ["高校生" "こうこうせい" "high school student"]
            ["主婦" "しゅふ" "housewife"]
            ["大学院生" "だいがくいんせい" "graduate student"]
            ["大学生" "だいがくせい" "college student"]
            ["弁護士" "べんごし" "lawyer"]
            ["お母さん" "おかあさん" "mother"]
            ["お父さん" "おとうさん" "father"]
            ["お姉さん" "おねえさん" "older sister"]
            ["お兄さん" "おにいさん" "older brother"]
            ["妹" "いもうと" "younger sister"]
            ["弟" "おとうと" "younger brother"]])
      (map #(make-tagged-item % "Genki Lesson 2")
           [["これ" "これ" "this one"]
            ["それ" "それ" "that one"]
            ["あれ" "あれ" "that one (over there)"]
            ["どれ" "どれ" "which one"]
            ["この" "この" "this ..."]
            ["その" "その" "that ..."]
            ["あの" "あの" "that ... (over there)"]
            ["どの" "どの" "which ..."]
            ["あそこ" "あそこ" "over there"]
            ["どこ" "どこ" "where"]
            ["だれ" "だれ" "who"]
            ["おいしい" "おいしい" "delicious"]
            ["魚" "さかな" "fish"]
            ["とんかつ" "とんかつ" "pork cutlet"]
            ["肉" "にく" "meat"]
            ["メニュー" "メニュー" "menu"]
            ["野菜" "やさい" "vegetable"]
            ["鉛筆" "えんぴつ" "pencil"]
            ["傘" "かさ" "umbrella"]
            ["かばん" "かばん" "bag"]
            ["靴" "くつ" "shoes"]
            ["財布" "さいふ" "wallet"]
            ["ジーンズ" "ジーンズ" "jeans"]
            ["辞書" "じしょ" "dictionary"]
            ["自転車" "じてんしゃ" "bicycle"]
            ["新聞" "しんぶん" "newspaper"]
            ["トイレ" "トイレ" "toilet; restroom"]
            ["時計" "とけい" "watch; clock"]
            ["ノート" "ノート" "notebook"]
            ["ペン" "ペン" "pen"]
            ["帽子" "ぼうし" "hat; cap"]
            ["本" "ほん" "book"]
            ["喫茶店" "きっさてん" "cafe"]
            ["銀行" "ぎんこう" "bank"]
            ["図書館" "としょかん" "library"]
            ["郵便局" "ゆうびんきょく" "post office"]
            ["経済" "けいざい" "economics"]
            ["いくら" "いくら" "how much"]
            ["〜円" "〜えん" "...yen"]
            ["高い" "たかい" "expensive; high"]
            ["いらっしゃいませ" "いらっしゃいませ" "Welcome (to our store)"]
            ["（〜を）おねがいします" "（〜を）おねがいします" "..., please."]
            ["（〜を）ください" "（〜を）ください" "Please give me..."]
            ["じゃあ" "じゃあ" "then...; if that is the case,..."]
            ["どうぞ" "どうぞ" "Please.; Here it is."]
            ["どうも" "どうも" "Thank you."]
            ["そこ" "そこ" "there"]
            ["ここ" "ここ" "here"]
            ["Tシャツ" "Tシャツ" "T-shirt"]])
      (map #(make-tagged-item % "Genki Lesson 3")
           [["映画" "えいが" "movie"]
            ["音楽" "おんがく" "music"]
            ["雑誌" "ざっし" "magazine"]
            ["スポーツ" "スポーツ" "sports"]
            ["デート" "デート" "date (romantic, not calendar)"]
            ["テニス" "テニス" "tennis"]
            ["テレビ" "テレビ" "TV"]
            ["アイスクリーム" "アイスクリーム" "ice cream"]
            ["朝ご飯" "あさごはん" "breakfast"]
            ["お酒" "おさけ" "sake; alcohol"]
            ["お茶" "おちゃ" "green tea"]
            ["コーヒー" "コーヒー" "coffee"]
            ["晩ご飯" "ばんごはん" "dinner"]
            ["ハンバーガー" "ハンバーガー" "hamburger"]
            ["昼ご飯" "ひるごはん" "lunch"]
            ["水" "みず" "water"]
            ["家" "いえ" "home; house"]
            ["家" "うち" "home; house; my place"]
            ["学校" "がっこう" "school"]
            ["朝" "あさ" "morning"]
            ["明日" "あした" "tomorrow"]
            ["いつ" "いつ" "when"]
            ["今日" "きょう" "today"]
            ["〜ごろ" "〜ごろ" "at about"]
            ["今晩" "こんばん" "tonight"]
            ["週末" "しゅうまつ" "weekend"]
            ["土曜日" "どようび" "Saturday"]
            ["日曜日" "にちようび" "Sunday"]
            ["毎日" "まいにち" "every day"]
            ["毎晩" "まいばん" "every night"]
            ["行く" "いく" "to go"]
            ["帰る" "かえる" "to go back; to return"]
            ["聞く" "きく" "to listen; to hear"]
            ["飲む" "のむ" "to drink"]
            ["話す" "はなす" "to speak; to talk"]
            ["読む" "よむ" "to read"]
            ["起きる" "おきる" "to get up"]
            ["食べる" "たべる" "to eat"]
            ["寝る" "ねる" "to sleep; to go to sleep"]
            ["見る" "みる" "to see; to look at; to watch"]
            ["来る" "くる" "to come"]
            ["する" "する" "to do"]
            ["勉強する" "べんきょうする" "to study"]
            ["いい" "いい" "good"]
            ["早い" "はやい" "early"]
            ["あまり+ negative" "あまり+ negative" "not much"]
            ["全然" "ぜんぜん + negative" "not at all"]
            ["たいてい" "たいてい" "usually"]
            ["ちょっと" "ちょっと" "a little"]
            ["時々" "ときどき" "sometimes"]
            ["よく" "よく" "often; much"]
            ["そうですね" "そうですね" "That's right.; Let me see."]
            ["でも" "でも" "but"]
            ["どうですか" "どうですか" "How about...?; How is...?"]])
      (map #(make-tagged-item % "Genki Lesson 4")
           [["アルバイト" "アルバイト" "part-time job"]
            ["買い物" "かいもの" "shopping"]
            ["クラス" "クラス" "class"]
            ["あなた" "あなた" "you"]
            ["犬" "いぬ" "dog"]
            ["お土産" "おみやげ" "souvenir"]
            ["子供" "こども" "child"]
            ["御飯" "ごはん" "rice; meal"]
            ["写真" "しゃしん" "picture; photograph"]
            ["机" "つくえ" "desk"]
            ["手紙" "てがみ" "letter"]
            ["猫" "ねこ" "cat"]
            ["パン" "パン" "bread"]
            ["人" "ひと" "person"]
            ["お寺" "おてら" "temple"]
            ["公園" "こうえん" "park"]
            ["スーパー" "スーパー" "supermarket"]
            ["デパート" "デパート" "department store"]
            ["バス停" "バスてい" "bus stop"]
            ["病院" "びょういん" "hospital"]
            ["ホテル" "ホテル" "hotel"]
            ["本屋" "ほんや" "bookstore"]
            ["町" "まち" "town; city"]
            ["レストラン" "レストラン" "restaurant"]
            ["昨日" "きのう" "yesterday"]
            ["さっき" "さっき" "a little while ago"]
            ["〜時間" "〜じかん" "hour"]
            ["一時間" "いちじかん" "one hour"]
            ["先週" "せんしゅう" "last week"]
            ["時" "とき" "when...; at the time of..."]
            ["火曜日" "かようび" "Tuesday"]
            ["水曜日" "すいようび" "Wednesday"]
            ["木曜日" "もくようび" "Thursday"]
            ["金曜日" "きんようび" "Friday"]
            ["会う" "あう" "to meet; to see (a person)"]
            ["ある" "ある" "there is ..."]
            ["買う" "かう" "to buy"]
            ["書く" "かく" "to write"]
            ["撮る" "とる" "to take (pictures)"]
            ["待つ" "まつ" "to wait"]
            ["わかる" "わかる" "to understand"]
            ["いる" "いる" "(a person) is in ...; stays at ..."]
            ["〜ぐらい" "〜ぐらい" "about (approximate measurement)"]
            ["ごめんなさい" "ごめんなさい" "I'm sorry."]
            ["だから" "だから" "so; therefore"]
            ["たくさん" "たくさん" "many; a lot"]
            ["〜と" "〜と" "together with (a person)"]
            ["どうして" "どうして" "why"]
            ["一人で" "ひとりで" "alone"]
            ["右" "みぎ" "right"]
            ["左" "ひだり" "left"]
            ["前" "まえ" "front"]
            ["後ろ" "うしろ" "back"]
            ["中" "なか" "inside"]
            ["上" "うえ" "on"]
            ["下" "した" "under"]
            ["近く" "ちかく" "near; near place"]
            ["隣" "となり" "next"]
            ["間" "あいだ" "between"]
            ["月曜日" "げつようび" "Monday"]
            ["いす" "いす" "chair"]
            ["メール" "メール" "e-mail"]])
      (map #(make-tagged-item % "Genki Lesson 5")
           [["海" "うみ" "sea"]
            ["切手" "きって" "postal stamps"]
            ["切符" "きっぷ" "ticket"]
            ["サーフィン" "サーフィン" "surfing"]
            ["宿題" "しゅくだい" "homework"]
            ["食べ物" "たべもの" "food"]
            ["誕生日" "たんじょうび" "birthday"]
            ["テスト" "テスト" "test"]
            ["天気" "てんき" "weather"]
            ["飲み物" "のみもの" "drink"]
            ["葉書" "はがき" "postcard"]
            ["バス" "バス" "bus"]
            ["飛行機" "ひこうき" "airplane"]
            ["部屋" "へや" "room"]
            ["僕" "ぼく" "I (used by men)"]
            ["休み" "やすみ" "holiday; day off; absence"]
            ["旅行" "りょこう" "travel"]
            ["新しい" "あたらしい" "new"]
            ["暑い" "あつい" "hot (weather)"]
            ["熱い" "あつい" "hot (objects)"]
            ["忙しい" "いそがしい" "busy (people/days)"]
            ["大きい" "おおきい" "large"]
            ["面白い" "おもしろい" "interesting; funny"]
            ["怖い" "こわい" "frightening"]
            ["寒い" "さむい" "cold (weather-not used for objects)"]
            ["楽しい" "たのしい" "fun"]
            ["小さい" "ちいさい" "small"]
            ["つまらない" "つまらない" "boring"]
            ["古い" "ふるい" "old (thing - not used for people)"]
            ["難しい" "むずかしい" "difficult"]
            ["やさしい" "やさしい" "easy (problem); kind (person)"]
            ["安い" "やすい" "inexpensive; cheap (thing)"]
            ["嫌い" "きらい（な）" "disgusted with; to dislike"]
            ["きれい（な）" "きれい（な）" "beautiful; clean"]
            ["元気" "げんき（な）" "healthy; energetic"]
            ["静か" "しずか（な）" "quiet"]
            ["好き" "すき（な）" "fond of; to like"]
            ["大嫌い" "だいきらい（な）" "to hate"]
            ["大好き" "だいすき（な）" "very fond of; to love"]
            ["にぎやか（な）" "にぎやか（な）" "lively"]
            ["暇" "ひま（な）" "not busy; to have a lot of free time"]
            ["泳ぐ" "およぐ" "to swim"]
            ["聞く" "きく" "to ask"]
            ["乗る" "のる" "to ride; to board"]
            ["やる" "やる" "to do; to perform"]
            ["出かける" "でかける" "to go out"]
            ["一緒に" "いっしょに" "together"]
            ["それから" "それから" "and then"]
            ["大丈夫"
             "だいじょうぶ"
             "It's okay.; Not to worry.; Everything is under control."]
            ["とても" "とても" "very"]
            ["どんな" "どんな" "what kind of..."]
            ["〜枚" "〜まい" "[counter for flat objects]"]
            ["〜まで" "〜まで" "to (a place); as far as (a place); till (a time)"]
            ["すごく" "すごく" "extremely"]])
      (map #(make-tagged-item % "Genki Lesson 6")
           [["CD　（シーディー）" "CD　（シーディー）" "CD"]
            ["お金" "おかね" "money"]
            ["お風呂" "おふろ" "bath"]
            ["漢字" "かんじ" "kanji; Chinese character"]
            ["教科書" "きょうかしょ" "textbook"]
            ["今週" "こんしゅう" "this week"]
            ["市民病院" "しみんびょういん" "Municipal Hospital"]
            ["次" "つぎ" "next"]
            ["パソコン" "パソコン" "personal computer"]
            ["電気" "でんき" "electricity"]
            ["電車" "でんしゃ" "train"]
            ["荷物" "にもつ" "baggage"]
            ["ページ" "ページ" "page"]
            ["窓" "まど" "window"]
            ["夜" "よる" "night"]
            ["来週" "らいしゅう" "next week"]
            ["来年" "らいねん" "next year"]
            ["大変" "たいへん（な）" "tough (situation)"]
            ["遊ぶ" "あそぶ" "to play; to spend time pleasantly"]
            ["急ぐ" "いそぐ" "to hurry"]
            ["お風呂に入る" "おふろにはいる" "to take a bath"]
            ["返す" "かえす" "to return (things)"]
            ["消す" "けす" "to turn off; to erase"]
            ["死ぬ" "しぬ" "to die"]
            ["座る" "すわる" "to sit down"]
            ["立つ" "たつ" "to stand up"]
            ["たばこを吸う" "たばこをすう" "to smoke"]
            ["使う" "つかう" "to use"]
            ["手伝う" "てつだう" "to help"]
            ["入る" "はいる" "to enter"]
            ["持つ" "もつ" "to carry; to hold"]
            ["休む" "やすむ" "to be absent (from...); to rest"]
            ["開ける" "あける" "to open (something)"]
            ["教える" "おしえる" "to teach; to instruct"]
            ["降りる" "おりる" "to get off"]
            ["借りる" "かりる" "to borrow"]
            ["閉める" "しめる" "to close (something)"]
            ["つける" "つける" "to turn on"]
            ["電話をかける" "でんわをかける" "to make a phone call"]
            ["忘れる" "わすれる" "to forget; to leave behind"]
            ["連れてくる" "つれてくる" "to bring (a person)"]
            ["持ってくる" "もってくる" "to bring (a thing)"]
            ["後で" "あとで" "later on"]
            ["遅く" "おそく" "(do something) late"]
            ["〜から" "〜から" "because ..."]
            ["結構です" "けっこうです" "That would be fine.; That wouldn't be necessary."]
            ["すぐ" "すぐ" "right away"]
            ["本当ですか" "ほんとうですか" "Really?"]
            ["ゆっくり" "ゆっくり" "slowly; leisurely; unhurriedly"]
            ["シャワー" "シャワー" "shower"]
            ["シャワーを浴びる" "シャワーをあびる" "to take a shower"]]))))
